export const modules = {
  dashboard: {
    title: "平台总览",
    subtitle: "统一查看学员、课程、成果认定、积分流水与就业信息",
  },
  learners: {
    title: "学员档案",
    subtitle: "维护终身学习用户的基础信息与账号状态",
    tableTitle: "学员列表",
    api: "/api/admin/learners",
    canCreate: true,
    canEdit: true,
    canDelete: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "username", label: "用户名" },
      { key: "realName", label: "姓名" },
      { key: "phone", label: "手机号" },
      { key: "email", label: "邮箱" },
      { key: "educationLevel", label: "学历" },
      { key: "status", label: "状态", badge: true },
    ],
    fields: [
      { key: "username", label: "用户名" },
      { key: "realName", label: "姓名" },
      { key: "phone", label: "手机号" },
      { key: "email", label: "邮箱" },
      { key: "educationLevel", label: "学历" },
      { key: "status", label: "状态", placeholder: "ACTIVE / DISABLED" },
    ],
  },
  courses: {
    title: "课程资源",
    subtitle: "管理课程编码、提供方、学分与积分信息",
    tableTitle: "课程列表",
    api: "/api/admin/courses",
    canCreate: true,
    canEdit: true,
    canDelete: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "courseCode", label: "课程编码" },
      { key: "courseName", label: "课程名称" },
      { key: "provider", label: "提供方" },
      { key: "category", label: "分类" },
      { key: "creditValue", label: "学分" },
      { key: "creditPoint", label: "积分" },
      { key: "status", label: "状态", badge: true },
    ],
    fields: [
      { key: "courseCode", label: "课程编码" },
      { key: "courseName", label: "课程名称" },
      { key: "provider", label: "提供方" },
      { key: "category", label: "分类" },
      { key: "creditValue", label: "学分", type: "number" },
      { key: "creditPoint", label: "积分", type: "number" },
      { key: "status", label: "状态", placeholder: "PUBLISHED / OFFLINE" },
    ],
  },
  products: {
    title: "积分商城管理",
    subtitle: "管理商城商品，编辑价格与库存",
    tableTitle: "商品列表",
    api: "/api/admin/products",
    canCreate: true,
    canEdit: true,
    canDelete: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "productCode", label: "商品编码" },
      { key: "productName", label: "商品名称" },
      { key: "productType", label: "类型", badge: true },
      { key: "creditPrice", label: "积分价格" },
      { key: "stock", label: "库存" },
      { key: "sold", label: "销量" },
      { key: "isActive", label: "上架", badge: true },
    ],
    fields: [
      { key: "productCode", label: "商品编码" },
      { key: "productName", label: "商品名称" },
      { key: "productType", label: "类型", placeholder: "COURSE / MERCHANDISE / CERTIFICATE / SERVICE" },
      { key: "creditPrice", label: "积分价格", type: "number" },
      { key: "stock", label: "库存 (-1=不限)", type: "number" },
      { key: "description", label: "描述", type: "textarea" },
      { key: "imageUrl", label: "图片URL" },
      { key: "isActive", label: "上架 (1=是, 0=否)", type: "number" },
    ],
  },
  "credit-accounts": {
    title: "积分账户",
    subtitle: "查看账户余额，执行开户、增加积分和消费积分操作",
    tableTitle: "积分账户列表",
    api: "/api/admin/credit-accounts",
    operations: { credit: true, openAccount: true, freeze: true },
    columns: [
      { key: "id", label: "ID" },
      { key: "learnerId", label: "学员 ID" },
      { key: "totalCredits", label: "累计积分" },
      { key: "availableCredits", label: "可用积分" },
      { key: "frozenCredits", label: "冻结积分" },
      { key: "accountStatus", label: "账户状态", badge: true },
    ],
    fields: [],
  },
  "credit-transactions": {
    title: "积分流水",
    subtitle: "追踪积分增加、消费和余额变化记录",
    tableTitle: "积分流水列表",
    api: "/api/admin/credit-transactions",
    columns: [
      { key: "id", label: "ID" },
      { key: "learnerId", label: "学员 ID" },
      { key: "accountId", label: "账户 ID" },
      { key: "transactionType", label: "类型", badge: true },
      { key: "amount", label: "数量" },
      { key: "balanceBefore", label: "变动前" },
      { key: "balanceAfter", label: "变动后" },
      { key: "sourceType", label: "来源" },
      { key: "remark", label: "备注" },
    ],
    fields: [],
  },
  achievements: {
    title: "成果认定",
    subtitle: "管理学习成果、证书、竞赛和实践成果审核",
    tableTitle: "成果列表",
    api: "/api/admin/achievements",
    canCreate: true,
    canEdit: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "learnerId", label: "学员 ID" },
      { key: "achievementName", label: "成果名称" },
      { key: "achievementType", label: "类型" },
      { key: "suggestedCredits", label: "建议积分" },
      { key: "auditStatus", label: "审核状态", badge: true },
      { key: "auditor", label: "审核人" },
    ],
    fields: [
      { key: "learnerId", label: "学员 ID", type: "number" },
      { key: "achievementName", label: "成果名称" },
      { key: "achievementType", label: "成果类型" },
      { key: "suggestedCredits", label: "建议积分", type: "number" },
      { key: "auditStatus", label: "审核状态", placeholder: "PENDING / APPROVED / REJECTED" },
      { key: "auditor", label: "审核人" },
    ],
  },
  "learning-records": {
    title: "学习记录",
    subtitle: "记录课程学习进度、成绩和完成状态",
    tableTitle: "学习记录列表",
    api: "/api/admin/learning-records",
    canCreate: true,
    canEdit: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "learnerId", label: "学员 ID" },
      { key: "courseId", label: "课程 ID" },
      { key: "progress", label: "进度" },
      { key: "score", label: "成绩" },
      { key: "result", label: "结果", badge: true },
      { key: "completedAt", label: "完成时间" },
    ],
    fields: [
      { key: "learnerId", label: "学员 ID", type: "number" },
      { key: "courseId", label: "课程 ID", type: "number" },
      { key: "progress", label: "进度", type: "number" },
      { key: "score", label: "成绩", type: "number" },
      { key: "result", label: "结果", placeholder: "PASSED / FAILED / LEARNING" },
    ],
  },
  "forum-posts": {
    title: "论坛管理",
    subtitle: "维护学习交流社区内容、板块和可见状态",
    tableTitle: "帖子列表",
    api: "/api/admin/forum-posts",
    canCreate: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "learnerId", label: "学员 ID" },
      { key: "title", label: "标题" },
      { key: "section", label: "板块" },
      { key: "replyCount", label: "回复数" },
      { key: "likeCount", label: "点赞数" },
      { key: "status", label: "状态", badge: true },
    ],
    fields: [
      { key: "learnerId", label: "学员 ID", type: "number" },
      { key: "title", label: "标题" },
      { key: "section", label: "板块" },
      { key: "content", label: "内容", type: "textarea" },
      { key: "replyCount", label: "回复数", type: "number" },
      { key: "likeCount", label: "点赞数", type: "number" },
      { key: "status", label: "状态", placeholder: "VISIBLE / HIDDEN" },
    ],
  },
  "flash-sales": {
    title: "秒杀管理",
    subtitle: "管理秒杀活动，设置商品、秒杀价、库存和活动时间",
    tableTitle: "秒杀活动列表",
    api: "/api/admin/flash-sales",
    canCreate: true,
    canEdit: true,
    canDelete: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "productName", label: "商品名称" },
      { key: "flashPrice", label: "秒杀价" },
      { key: "stock", label: "库存" },
      { key: "beginTime", label: "开始时间" },
      { key: "endTime", label: "结束时间" },
      { key: "status", label: "状态", badge: true },
    ],
    fields: [
      { key: "productId", label: "商品ID", type: "number" },
      { key: "productName", label: "商品名称" },
      { key: "originPrice", label: "原价", type: "number" },
      { key: "flashPrice", label: "秒杀价", type: "number" },
      { key: "stock", label: "秒杀库存", type: "number" },
      { key: "beginTime", label: "开始时间", placeholder: "yyyy-MM-dd HH:mm:ss" },
      { key: "endTime", label: "结束时间", placeholder: "yyyy-MM-dd HH:mm:ss" },
      { key: "status", label: "状态", placeholder: "UPCOMING / ACTIVE / ENDED" },
    ],
  },
  jobs: {
    title: "招聘求职",
    subtitle: "发布和维护面向学习者的招聘岗位",
    tableTitle: "岗位列表",
    api: "/api/admin/jobs",
    canCreate: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "companyName", label: "公司" },
      { key: "positionName", label: "岗位" },
      { key: "city", label: "城市" },
      { key: "contact", label: "联系方式" },
      { key: "status", label: "状态", badge: true },
    ],
    fields: [
      { key: "companyName", label: "公司" },
      { key: "positionName", label: "岗位" },
      { key: "city", label: "城市" },
      { key: "requirement", label: "要求", type: "textarea" },
      { key: "contact", label: "联系方式" },
      { key: "status", label: "状态", placeholder: "OPEN / CLOSED" },
    ],
  },
};

export const menu = [
  { key: "dashboard", label: "平台总览", icon: "LayoutDashboard" },
  { key: "learners", label: "学员档案", icon: "Users" },
  { key: "courses", label: "课程资源", icon: "BookOpen" },
  { key: "products", label: "积分商城", icon: "ShoppingBag" },
  { key: "flash-sales", label: "秒杀管理", icon: "Zap" },
  { key: "credit-accounts", label: "积分账户", icon: "WalletCards" },
  { key: "credit-transactions", label: "积分流水", icon: "ReceiptText" },
  { key: "achievements", label: "成果认定", icon: "Award" },
  { key: "learning-records", label: "学习记录", icon: "ClipboardList" },
  { key: "forum-posts", label: "论坛管理", icon: "MessagesSquare" },
  { key: "jobs", label: "招聘求职", icon: "BriefcaseBusiness" },
];
